/**
 * GoodVibesFilter | filtered artist storage
 */

exports.filteredArtistsList = [
    "01099",
    "187 Strassenbande",
    "AK AUSSERKONTROLLE",
    "AVO",
    "Apache 207",
    "Azet",
    "Bausa",
    "Bonez MC",
    "Bozza",
    "Capital Bra",
    "Capo",
    "Dardan",
    "Fler",
    "Gustav",
    "Gzuz",
    "Jamule",
    "KASIMIR1441",
    "KC Rebell",
    "Loredana",
    "Luciano",
    "Nimo",
    "Pashanim",
    "RAF Camora",
    "RIN",
    "Samra",
    "Shindy",
    "Shirin David",
    "Summer Cem",
    "Ufo361",
    "Zachi",
]
